[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
unite = "BSCyxZZC45jfhd7dTTGgqHi2zugA36ydofso7FNdeK8X"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/bharath_kumar_shetty/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
